Repository Atcha-Project/Atcha-iOS, pull requests merged in 2025-07, with the labels that each got.

#55 [REFACTOR] 회원가입 API 수정
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Onboarding/RegisterLocation/RegisterLocationViewModel.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewModel.swift
Labels: 🛠️ Refactor

#65 [FEAT] 지도 관련 메인 View 처리
  .gitignore
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/App/DIContainer/Location/LocationDIContainer.swift
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/Data/Repository/Location/FetchTaxiFareRepositoryImpl.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/.DS_Store
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/.DS_Store
  Atcha-iOS/Domain/Repository/Location/FetchTaxiFareRepository.swift
  Atcha-iOS/Domain/UseCase/Location/FetchTaxiFareUseCase.swift
  Atcha-iOS/Presentation/Common/BaseViewController.swift
  Atcha-iOS/Presentation/Location/Coordinator/MainRoute.swift
  Atcha-iOS/Presentation/Location/MapViewController.swift
  Atcha-iOS/Presentation/Location/MapViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainSearchBottomView.swift
  Atcha-iOS/Presentation/Location/View/TMapContainerView.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageViewController.swift
  Secrets.xcconfig
Labels: 👾 Feat

#69 [DESIGN] 교통수단 노선 코드 추가 및 Defualt 추가
  Atcha-iOS.xcodeproj/xcuserdata/wodnd.xcuserdatad/xcschemes/xcschememanagement.plist
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Airport/airport-bus.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Airport/airport-bus.imageset/h36.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Airport/airport-bus.imageset/h36@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Airport/airport-bus.imageset/h36@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/deafult-subway.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/deafult-subway.imageset/Route-circle.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/deafult-subway.imageset/Route-circle@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/deafult-subway.imageset/Route-circle@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-bus.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-bus.imageset/h36.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-bus.imageset/h36@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-bus.imageset/h36@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-getOff.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-getOff.imageset/Ellipse 1733.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-getOff.imageset/Ellipse 1733@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Default/default-getOff.imageset/Ellipse 1733@3x.png
  Atcha-iOS/DesignSource/AtchaImage/TransportationIconView.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseCell.swift
Labels: 🎨 Design

#75 [FEAT] 온보딩 리팩토링 작업 진행 및 화면 Flow처리 작업진행
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppDelegate.swift
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/App/DIContainer/AppDIContainer.swift
  Atcha-iOS/App/DIContainer/CoordinatorFactory.swift
  Atcha-iOS/App/DIContainer/Location/LocationDIContainer.swift
  Atcha-iOS/App/DIContainer/Login/LoginDIContainer.swift
  Atcha-iOS/App/DIContainer/Onboarding/OnboardingDIContainer.swift
  Atcha-iOS/App/DIContainer/Setting/PushRegisterDIContainer.swift
  Atcha-iOS/App/DIContainer/Splash/SplashDIContainer.swift
  Atcha-iOS/App/DIContainer/User/Home/HomeRegisterDIContainer.swift
  Atcha-iOS/Core/Share/LocationStateHolder.swift
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/Data/Model/LocationDTO/SearchLocationRequest.swift
  Atcha-iOS/Data/Model/LocationDTO/SearchLocationResponse.swift
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/Data/Repository/Location/AddressRepositoryImpl.swift
  Atcha-iOS/Data/Repository/LoginRepositoryImpl.swift
  Atcha-iOS/Data/Repository/OnboardingRepositoryImpl.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/DesignSource/AtchaFont/AtchaFont.swift
  Atcha-iOS/DesignSource/AtchaNavigationBar/AtchaNavigationBar.swift
  Atcha-iOS/DesignSource/AtchaNavigationBar/TitleNavigationBar.swift
  Atcha-iOS/Domain/Entity/Location.swift
  Atcha-iOS/Domain/Repository/Location/AddressRepository.swift
  Atcha-iOS/Domain/Repository/LoginRepository.swift
  Atcha-iOS/Domain/Repository/User/UserRepository.swift
  Atcha-iOS/Domain/Repository/UserRepository.swift
  Atcha-iOS/Domain/UseCase/Location/SearchAddressUseCase.swift
  Atcha-iOS/Domain/UseCase/LoginUseCase.swift
  Atcha-iOS/Domain/UseCase/User/SignUpUseCase.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewController.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewModel.swift
  Atcha-iOS/Presentation/Location/View/HomeRegisterBottomView.swift
  Atcha-iOS/Presentation/Location/View/TMapContainerView.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Onboarding/OnboardingRoute.swift
  Atcha-iOS/Presentation/Onboarding/PushAlarm/PushAlarmViewController.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewModel.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/AlarmTimeOption.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/Splash/Coordinator/SplashCoordinator.swift
  Atcha-iOS/Presentation/Splash/Coordinator/SplashRouter.swift
  Atcha-iOS/Presentation/Splash/SplashViewController.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
Labels: 👾 Feat, 🛠️ Refactor

#79 [FEAT] 최근 검색어 기능 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/Network/API/APIResponse.swift
  Atcha-iOS/Core/Network/API/APIServiceImpl.swift
  Atcha-iOS/Data/Model/SearchHistoryDTO/AddRecentSearchRequest.swift
  Atcha-iOS/Data/Model/SearchHistoryDTO/FetchRecentSearchRequest.swift
  Atcha-iOS/Data/Repository/Location/AddressRepositoryImpl.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x-gray.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x-gray.imageset/x-filled.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x-gray.imageset/x-filled@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x-gray.imageset/x-filled@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x.imageset/name=x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x.imageset/name=x@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/X/x.imageset/name=x@3x.png
  Atcha-iOS/Domain/Repository/Location/AddressRepository.swift
  Atcha-iOS/Domain/UseCase/Location/SearchAddressUseCase.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewController.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewModel.swift
Labels: 👾 Feat

#80 [FEAT] 권한 요청 관련 로직수행
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppDelegate.swift
  Atcha-iOS/App/DIContainer/AppDIContainer.swift
  Atcha-iOS/App/DIContainer/Location/LocationDIContainer.swift
  Atcha-iOS/App/DIContainer/Onboarding/OnboardingDIContainer.swift
  Atcha-iOS/App/DIContainer/Permission/PermissionDIContainer.swift
  Atcha-iOS/App/DIContainer/Permission/PermissionType.swift
  Atcha-iOS/App/DIContainer/User/Home/HomeRegisterDIContainer.swift
  Atcha-iOS/Core/Util/LocationService.swift
  Atcha-iOS/Data/Repository/Location/RequestLocationAuthorizationRepositoryImpl.swift
  Atcha-iOS/DesignSource/AtchaFont/AtchaFont.swift
  Atcha-iOS/Domain/Repository/Location/RequestLocationAuthorizationRepository.swift
  Atcha-iOS/Domain/UseCase/Location/RequestLocationAuthorizationUseCase.swift
  Atcha-iOS/Domain/UseCase/OnboardingUseCase.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewModel.swift
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Onboarding/OnboardingRoute.swift
  Atcha-iOS/Presentation/Onboarding/Permission/PermissionViewController.swift
  Atcha-iOS/Presentation/Onboarding/Permission/PermissionViewModel.swift
  Atcha-iOS/Presentation/Onboarding/RegisterLocation/RegisterLocationViewController.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
Labels: 👾 Feat

#83 Refactor/#82
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/Util/String+Ext.swift
  Atcha-iOS/Data/Model/CourseSearchDTO/CourseSearchRequest.swift
  Atcha-iOS/Data/Model/CourseSearchDTO/CourseSearchResponse.swift
  Atcha-iOS/Data/Model/LocationDTO/FetchRecentSearchResponse.swift
  Atcha-iOS/Data/Repository/CourseRepositoryImpl.swift
  Atcha-iOS/Data/Repository/Location/AddressRepositoryImpl.swift
  Atcha-iOS/Domain/Entity/Course.swift
  Atcha-iOS/Domain/Repository/CourseRepository.swift
  Atcha-iOS/Domain/Repository/Location/AddressRepository.swift
  Atcha-iOS/Domain/UseCase/CourseUseCase.swift
  Atcha-iOS/Domain/UseCase/Location/SearchAddressUseCase.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewController.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewModel.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseCell.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
Labels: 👾 Feat, 🛠️ Refactor

#84 [FEAT] 메인 -> 마이페이지 -> 상세 Flow개발
  Atcha-iOS/App/DIContainer/AppDIContainer.swift
  Atcha-iOS/App/DIContainer/CoordinatorFactory.swift
  Atcha-iOS/App/DIContainer/Location/LocationDIContainer.swift
  Atcha-iOS/App/DIContainer/Onboarding/OnboardingDIContainer.swift
  Atcha-iOS/App/DIContainer/Permission/PermissionDIContainer.swift
  Atcha-iOS/App/DIContainer/User/MyPageDIContainer.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageViewController.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageViewModel.swift
Labels: 🐞 Bugfix, 👾 Feat, 🛠️ Refactor

#86 [FEAT] 출발지 설정 기능 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/Course/CourseDIContainer.swift
  Atcha-iOS/App/DIContainer/Location/LocationDIContainer.swift
  Atcha-iOS/Presentation/Course/Coordinator/CourseModifyCoordinator.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewController.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewModel.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseCell.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseTabCell.swift
  Atcha-iOS/Presentation/Course/CourseSetting/CourseSettingViewController.swift
  Atcha-iOS/Presentation/Course/CourseSetting/CourseSettingViewModel.swift
  Atcha-iOS/Presentation/Course/CourseSetting/OriginSettingBottomView.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
Labels: 👾 Feat

#87 [FEAT] 회원 탈퇴 기능 개발 완료
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/App/DIContainer/Main/MainDIContainer.swift
  Atcha-iOS/App/DIContainer/Setting/MyAccountDIContainer.swift
  Atcha-iOS/App/DIContainer/User/MyPageDIContainer.swift
  Atcha-iOS/Core/Network/Token/TokenInterceptor.swift
  Atcha-iOS/Core/Network/Token/TokenStorage.swift
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/Data/Model/RefreshTokenResponse.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/User/UserRepository.swift
  Atcha-iOS/Domain/UseCase/User/LogoutuseCase.swift
  Atcha-iOS/Domain/UseCase/User/SignOutUseCase.swift
  Atcha-iOS/Presentation/Login/LoginViewModel.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountItem.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewController.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/Cell/MyPageCell.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageItem.swift
Labels: 👾 Feat, 🛠️ Refactor

#89 [FEAT] 약관 페이지 연동
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/WebView/WebViewController.swift
Labels: 👾 Feat

#91 [FEAT] 마이페이지 우리집 변경 로직 추가
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/Onboarding/OnboardingDIContainer.swift
  Atcha-iOS/App/DIContainer/User/Home/HomeRegisterDIContainer.swift
  Atcha-iOS/App/DIContainer/User/MyPageDIContainer.swift
  Atcha-iOS/Core/Util/UINavigationController+Ext.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewModel.swift
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Onboarding/HomeRouter.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageHomeRegisterRouter.swift
Labels: 👾 Feat

#93 [FEAT] 버튼 폰트 수정 및 네비게이션 바 추가
  Atcha-iOS/DesignSource/AtchaButton/AtchaButton.swift
  Atcha-iOS/DesignSource/AtchaNavigationBar/AtchaNavigationBar.swift
  Atcha-iOS/DesignSource/AtchaNavigationBar/TitleNavigationBar.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageViewController.swift
Labels: 👾 Feat, 🛠️ Refactor

#97 [FEAT] 스플래시 / 로그인 화면 개발 완료
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Base.lproj/LaunchScreen.storyboard
  Atcha-iOS/Core/Network/API/APIServiceImpl.swift
  Atcha-iOS/Core/Network/Token/TokenStorage.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/AtchaCharacter/img_Atcha_character.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/AtchaCharacter/img_Atcha_character.imageset/img_Atcha_character.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/AtchaCharacter/img_Atcha_character.imageset/img_Atcha_character@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/AtchaCharacter/img_Atcha_character.imageset/img_Atcha_character@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step1.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step1.imageset/Step1.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step1.imageset/Step1@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step1.imageset/Step1@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step2.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step2.imageset/Step2.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step2.imageset/Step2@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step2.imageset/Step2@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step3.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step3.imageset/Step3.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step3.imageset/Step3@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step3.imageset/Step3@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step5.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step5.imageset/Step5.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step5.imageset/Step5@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Step5.imageset/Step5@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/img_Step1.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/img_Step1@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/img_Step1@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/img_Step2.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/img_Step2@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/img_Step2@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/img_Step3.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/img_Step3@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/img_Step3@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/step4.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/step4.imageset/step4.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/step4.imageset/step4@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/step4.imageset/step4@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash_BG.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash_BG.imageset/Splash_BG.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash_BG.imageset/Splash_BG@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash_BG.imageset/Splash_BG@3x.png
  Atcha-iOS/Presentation/Login/LoginIntroCell.swift
  Atcha-iOS/Presentation/Login/LoginItnro.swift
  Atcha-iOS/Presentation/Login/LoginViewController.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/Splash/SplashViewController.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewModel.swift
Labels: 👾 Feat

#104 [REFACTOR] 온보딩 UI 수정 및 앱 Icon 설정
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/100.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/102.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/1024.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/108.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/114.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/120.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/128.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/144.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/152.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/16.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/167.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/172.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/180.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/196.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/20.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/216.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/234.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/256.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/258.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/29.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/32.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/40.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/48.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/50.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/512.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/55.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/57.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/58.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/60.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/64.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/66.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/72.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/76.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/80.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/87.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/88.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/92.png
  Atcha-iOS/DesignSource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/img_notification.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/img_notification.imageset/Notification.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/img_notification.imageset/Notification@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/img_notification.imageset/Notification@3x.png
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/AlarmTimeOption.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
Labels: 👾 Feat, 🛠️ Refactor

#106 [REFACTOR] 경로 탐색 & 경로 수정 코드 정리
  Atcha-iOS/Core/Network/Token/TokenInterceptor.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewController.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewModel.swift
  Atcha-iOS/Presentation/Login/LoginViewModel.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/AlarmTimeOption.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
Labels: 🛠️ Refactor

#112 [FEAT] 택시비 말풍선 관련 로직 추가
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/Storages/UserDefaults/UserDefaultsWrapper.swift
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/Data/Model/LocationDTO/FetchTaxiFareRequest.swift
  Atcha-iOS/Data/Model/LocationDTO/ReverseGeocodeLocationResponse.swift
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/DesignSource/AtchaBallon/AtcahaInsetLabel.swift
  Atcha-iOS/DesignSource/AtchaBallon/AtchaBallon.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Triangle.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Triangle.imageset/Triangle.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Triangle.imageset/Triangle@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Triangle.imageset/Triangle@3x.png
  Atcha-iOS/Domain/UseCase/Location/SearchAddressUseCase.swift
  Atcha-iOS/Presentation/Course/CourseSetting/CourseSettingViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainSearchBottomView.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
Labels: 👾 Feat

#115 [FEAT] 사용자 출발 전 UI 개발
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/Course/CourseDIContainer.swift
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/Data/Model/CourseSearchDTO/CourseSearchResponse.swift
  Atcha-iOS/DesignSource/AtchaImage/TransportationIconView.swift
  Atcha-iOS/Domain/Entity/Course.swift
  Atcha-iOS/Presentation/Course/Coordinator/CourseModifyCoordinator.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainDepartBottomView.swift
  Atcha-iOS/Presentation/Location/View/TMapContainerView.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
Labels: 👾 Feat, 🛠️ Refactor

#116 [FEAT] 메인 화면 이후 -> 화면 전환 로직 추가
  Atcha-iOS/Core/Util/String+Ext.swift
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/DesignSource/AtchaBallon/AtchaBallon.swift
  Atcha-iOS/DesignSource/AtchaImage/TransportationIconView.swift
  Atcha-iOS/Domain/Entity/Course.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseCell.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainDepartBottomView.swift
  Atcha-iOS/Presentation/Location/View/TMapContainerView.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
Labels: 👾 Feat
