Repository Atcha-Project/Atcha-iOS, pull requests merged in 2025-08, with the labels that each got.

#124 [FEAT] 버스 상세 기록 로직 추가
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/Data/Model/CourseSearchDTO/CourseSearchResponse.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Marker/SmallEndMarker.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Marker/SmallEndMarker.imageset/SmallEndMarker.svg
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Marker/SmallStartMarker.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Color/Marker/SmallStartMarker.imageset/SmallStartMarker.svg
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/DotLine.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/DotLine.imageset/DotLine.svg
  Atcha-iOS/Domain/Entity/Course.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/Cell/DetailRouteBusCell.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/Cell/DetailRouteEndCell.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/Cell/DetailRouteStartCell.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/Cell/DetailRouteSubwayCell.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/Cell/DetailRouteWalkCell.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/DetailRouteInfoBottomView.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/DetailRouteInfoViewModel.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteInfo/DetailRouteProgressView.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteViewController.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
Labels: 👾 Feat

#131 [FEAT] RouteLine 코드로 변경
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/bus-route-circle.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/bus-route-circle.imageset/bus-route-circle.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/bus-route-circle.imageset/bus-route-circle@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/bus-route-circle.imageset/bus-route-circle@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/rotation.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/rotation.imageset/rotation.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/rotation.imageset/rotation@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Course/BusRoute/rotation.imageset/rotation@3x.png
  Atcha-iOS/Presentation/BusDetail/BusDetailViewController.swift
  Atcha-iOS/Presentation/BusDetail/BusRouteCell.swift
  Atcha-iOS/Presentation/BusDetail/RouteLineView.swift
Labels: 👾 Feat

#135 [FEAT] 잠금화면 Flow연동
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/App/DIContainer/AppDIContainer.swift
  Atcha-iOS/App/DIContainer/CoordinatorFactory.swift
  Atcha-iOS/App/DIContainer/LockScreen/LockScreenDIConatiner.swift
  Atcha-iOS/Core/Manager/AlarmManager.swift
  Atcha-iOS/Core/Storages/UserDefaults/UserDefaultsKey.swift
  Atcha-iOS/Info.plist
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Lock/Coordinator/LockScreenCoordinator.swift
  Atcha-iOS/Presentation/Lock/LockViewController.swift
  Atcha-iOS/Presentation/Lock/LockViewModel.swift
  Atcha-iOS/Presentation/Login/LoginViewModel.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/Splash/Coordinator/SplashRouter.swift
  Atcha-iOS/Presentation/Splash/SplashViewController.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
  Atcha-iOS/silent.mp3
  Atcha-iOS/siren.mp3
Labels: 👾 Feat

#139 [FEAT] 탈퇴 사유 기능 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/Setting/MyAccountDIContainer.swift
  Atcha-iOS/App/DIContainer/User/MyPageDIContainer.swift
  Atcha-iOS/Core/Util/UITextView+Ext.swift
  Atcha-iOS/Data/Repository/CourseRepositoryImpl.swift
  Atcha-iOS/DesignSource/AtchaButton/AtchaButton.swift
  Atcha-iOS/DesignSource/AtchaList/AtchaList.swift
  Atcha-iOS/DesignSource/AtchaTextBox/WithDrawTextBox.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewController.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawOption.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewController.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewModel.swift
Labels: 👾 Feat

#141 [BUGFIX] 집주소 등록 수정
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/User/Home/HomeRegisterDIContainer.swift
  Atcha-iOS/Data/Model/UserInfoModifyDTO/HomeModify/HomePatchRequest.swift
  Atcha-iOS/Data/Model/UserInfoModifyDTO/HomeModify/HomePatchResponse.swift
  Atcha-iOS/Data/Repository/CourseRepositoryImpl.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/User/UserRepository.swift
  Atcha-iOS/Domain/UseCase/User/HomePatchUseCase.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewModel.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
Labels: 🐞 Bugfix

#142 [FEAT] 알람 이후 메인 화면 로직 고도화
  Atcha-iOS/App/DIContainer/Main/MainDIContainer.swift
  Atcha-iOS/Domain/Entity/Course.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainDepartBottomView.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
Labels: 👾 Feat

#145 [FEAT] 스트리밍용 토큰 재발급 기능 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/User/Home/HomeRegisterDIContainer.swift
  Atcha-iOS/Data/Model/UserDTO/WithdrawRequest.swift
  Atcha-iOS/Data/Repository/CourseRepositoryImpl.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/User/UserRepository.swift
  Atcha-iOS/Domain/UseCase/User/SignOutUseCase.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseCell.swift
  Atcha-iOS/Presentation/Location/View/LastTrainSearchBottomView.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewController.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewModel.swift
Labels: 👾 Feat

#147 [FEAT] 알림 빈도 API 연결 및 탈퇴시 locationState 초기화
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/AppDIContainer.swift
  Atcha-iOS/App/DIContainer/Onboarding/OnboardingDIContainer.swift
  Atcha-iOS/App/DIContainer/Setting/PushRegisterDIContainer.swift
  Atcha-iOS/App/DIContainer/User/MyPageDIContainer.swift
  Atcha-iOS/Core/Share/LocationStateHolder.swift
  Atcha-iOS/Data/Model/UserInfoPatchDTO/HomePatch/HomePatchRequest.swift
  Atcha-iOS/Data/Model/UserInfoPatchDTO/PushAlarmPatch/PushAlarmPatchRequest.swift
  Atcha-iOS/Data/Model/UserInfoPatchDTO/UserInfoPatchResponse.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/User/UserRepository.swift
  Atcha-iOS/Domain/UseCase/User/HomePatchUseCase.swift
  Atcha-iOS/Domain/UseCase/User/PushAlarmPatchUseCase.swift
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/User/AlarmSetting/AlarmSettingViewController.swift
  Atcha-iOS/Presentation/User/AlarmSetting/AlarmSettingViewModel.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewModel.swift
Labels: 👾 Feat

#151 [FEAT] 알림등록 연결
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/Course/CourseDIContainer.swift
  Atcha-iOS/Core/Storages/UserDefaults/UserDefaultsKey.swift
  Atcha-iOS/Data/Model/AlarmDTO/AlarmRefreshResponse.swift
  Atcha-iOS/Data/Model/AlarmDTO/AlarmRequest.swift
  Atcha-iOS/Data/Repository/AlarmRepositoryImpl.swift
  Atcha-iOS/Domain/Entity/AlarmRefresh.swift
  Atcha-iOS/Domain/Repository/AlarmRepository.swift
  Atcha-iOS/Domain/UseCase/AlarmUseCase.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewModel.swift
Labels: 👾 Feat

#156 [FEAT] 알람 로직 관련 고도화
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/SceneDelegate.swift
  Atcha-iOS/Core/Manager/AlarmManager.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
  Atcha-iOS/siren.mp3
Labels: 👾 Feat

#161 [FEAT] 지도 상세 로직 고도화
  Atcha-iOS/Core/ViewWrapper/TMapWrapper.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteViewController.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
Labels: 🐞 Bugfix, 👾 Feat

#163 [BUGFIX] 데이터 일부 표시 차단 및 기능 수정
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/DesignSource/AtchaNavigationBar/SearchNavigationBar.swift
  Atcha-iOS/DesignSource/AtchaTextField/RegisterTextField.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseCell.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseStepView.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Location/View/HomeRegisterBottomView.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewController.swift
  Atcha-iOS/TMapSDK.framework/Assets.car
  Atcha-iOS/TMapSDK.framework/Headers/TMapSDK-Swift.h
  Atcha-iOS/TMapSDK.framework/Headers/TMapSDK.h
  Atcha-iOS/TMapSDK.framework/Headers/TrafficLine.h
  Atcha-iOS/TMapSDK.framework/Info.plist
  Atcha-iOS/TMapSDK.framework/Modules/TMapSDK.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo
  Atcha-iOS/TMapSDK.framework/Modules/TMapSDK.swiftmodule/arm64-apple-ios.abi.json
  Atcha-iOS/TMapSDK.framework/Modules/TMapSDK.swiftmodule/arm64-apple-ios.private.swiftinterface
  Atcha-iOS/TMapSDK.framework/Modules/TMapSDK.swiftmodule/arm64-apple-ios.swiftdoc
  Atcha-iOS/TMapSDK.framework/Modules/TMapSDK.swiftmodule/arm64-apple-ios.swiftinterface
  Atcha-iOS/TMapSDK.framework/Modules/TMapSDK.swiftmodule/arm64-apple-ios.swiftmodule
  Atcha-iOS/TMapSDK.framework/Modules/module.modulemap
  Atcha-iOS/TMapSDK.framework/TMapSDK
  Atcha-iOS/TMapSDK.framework/_CodeSignature/CodeResources
  Atcha-iOS/TMapSDK.framework/vsmRoute.fbs
Labels: 🐞 Bugfix

#166 [FEAT] 팝업 개발
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Presentation/Popup/AtchaPopupInfo.swift
  Atcha-iOS/Presentation/Popup/AtchaPopupViewController.swift
  Atcha-iOS/Presentation/Popup/AtchaPopupViewModel.swift
Labels: 👾 Feat

#169 [FEAT] 알림 등록 버튼 추가 및 팝업 기능 연결 #168
  Atcha-iOS/App/DIContainer/Route/RouteDIContainer.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/bell-outlined.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/bell-outlined@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/bell-outlined@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/name=bell.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/name=bell@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Bell/bell-outlined.imageset/name=bell@3x.png
  Atcha-iOS/Presentation/Location/Coordinator/MainRoute.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteViewController.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Main/MainCoordinator.swift
  Atcha-iOS/Presentation/Popup/AtchaPopupViewController.swift
  Atcha-iOS/Presentation/User/MyAccount/MyAccountViewController.swift
  Atcha-iOS/Presentation/User/Withdraw/WithdrawViewController.swift
Labels: 👾 Feat

#171 [REFACTOR] 경로 탐색 결과 없음 UI 고도화
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Data/Model/LocationDTO/CheckServiceRegion/CheckServiceRegionRequest.swift
  Atcha-iOS/Data/Model/LocationDTO/SearchLocation/SearchLocationRequest.swift
  Atcha-iOS/Data/Model/LocationDTO/SearchLocation/SearchLocationResponse.swift
  Atcha-iOS/Data/Repository/Location/AddressRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/Location/AddressRepository.swift
  Atcha-iOS/Domain/UseCase/Location/SearchAddressUseCase.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewController.swift
  Atcha-iOS/Presentation/Course/CourseModify/CourseModifyViewModel.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Location/SearchLocation/SearchLocationViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainSearchBottomView.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
Labels: 👾 Feat, 🛠️ Refactor

#177 [FEAT] 소리, 진동, 음량조절 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/Manager/AlarmManager.swift
  Atcha-iOS/Core/Storages/UserDefaults/UserDefaultsKey.swift
  Atcha-iOS/Core/Storages/UserDefaults/UserDefaultsWrapper.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Volume/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Volume/volumeThumb.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Volume/volumeThumb.imageset/volumeThumb.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Volume/volumeThumb.imageset/volumeThumb@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Normal/Volume/volumeThumb.imageset/volumeThumb@3x.png
  Atcha-iOS/Presentation/Setting/PushAlarm/AlarmTimeOption.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmBottomView.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmOption.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageCoordinator.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageViewController.swift
  Atcha-iOS/Presentation/User/MyPage/MyPageViewModel.swift
Labels: 👾 Feat

#178 [FEAT] 알람 로직 고도화
  Atcha-iOS/Core/Manager/AlarmManager.swift
Labels: 🐞 Bugfix, 👾 Feat

#182 [FEAT] 네트워크 재연결 팝업 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/Core/Network/NetworkPatcher.swift
  Atcha-iOS/Core/Network/NetworkReconnectView.swift
  Atcha-iOS/Presentation/Common/BaseViewController.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/View/TMapContainerView.swift
Labels: 👾 Feat

#184 [FEAT] 배차 긴 버스 경로 선택 시 팝업
  Atcha-iOS/Presentation/Course/CourseSearch/CourseSearchViewController.swift
  Atcha-iOS/Presentation/Location/DetailRoute/DetailRouteViewController.swift
  Atcha-iOS/Presentation/Popup/AtchaPopupInfo.swift
  Atcha-iOS/Presentation/Popup/AtchaPopupViewController.swift
Labels: 👾 Feat

#186 [FEAT] 알람 진동 설정 소리 로직 연동
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmBottomView.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
Labels: 👾 Feat

#187 [REFACTOR] 디자인 디테일 수정
  Atcha-iOS/DesignSource/AtchaToast/AtchaToast.swift
  Atcha-iOS/Presentation/Course/CourseSetting/CourseSettingViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewController.swift
  Atcha-iOS/Presentation/User/Home/HomeFindViewModel.swift
Labels: 🛠️ Refactor

#192 [FEAT] 알람 관련 로직 고도화
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppDelegate.swift
  Atcha-iOS/Core/Manager/AlarmManager.swift
  Atcha-iOS/Core/Notification/NotificationKeys.swift
  Atcha-iOS/Presentation/Common/BaseViewModel.swift
  Atcha-iOS/Presentation/Location/MainViewController.swift
  Atcha-iOS/Presentation/Location/MainViewModel.swift
  Atcha-iOS/Presentation/Location/View/LastTrainSearchBottomView.swift
  Atcha-iOS/Presentation/Lock/LockViewModel.swift
  Atcha-iOS/Presentation/Setting/PushAlarm/PushAlarmViewController.swift
Labels: 🐞 Bugfix, 👾 Feat
