Repository Atcha-Project/Atcha-iOS, pull requests merged in 2025-06, with the labels that each got.

#12 [DESIGN] Toast 개발
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/Util/UIView+Ext.swift
  Atcha-iOS/DesignSource/AtchaToast/AtchaToast.swift
Labels: 🎨 Design

#19 [FEAT] 프로젝트 기본 구조 샘플 작업완료
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppDelegate.swift
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/App/DIContainer/DIContainer.swift
  Atcha-iOS/App/SceneDelegate.swift
  Atcha-iOS/Base.lproj/LaunchScreen.storyboard
  Atcha-iOS/Data/Network/APIClient.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Atcha.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Atcha.imageset/img_Atcha.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Atcha.imageset/img_Atcha@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Atcha.imageset/img_Atcha@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Splash.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Splash.imageset/img_Splash.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Splash.imageset/img_Splash@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/img_Splash.imageset/img_Splash@3x.png
  Atcha-iOS/Domain/Entity/User.swift
  Atcha-iOS/Domain/Repository/UserRepository.swift
  Atcha-iOS/Domain/UseCase/FetchUserUseCase.swift
  Atcha-iOS/Presentation/Splash/SplashViewController.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
Labels: ⚙️ Setting, 👾 Feat

#24 [FEAT] 카카오, 애플 로그인 화면 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/DIContainer/DIContainer.swift
  Atcha-iOS/Data/Model/LoginDTO.swift
  Atcha-iOS/Data/Repository/LoginRepositoryImpl.swift
  Atcha-iOS/Data/Repository/LoginUseCaseImpl.swift
  Atcha-iOS/DesignSource/AtchaColor/AtchaColor.swift
  Atcha-iOS/DesignSource/AtchaColor/Colors.xcassets/Etc/Contents.json
  Atcha-iOS/DesignSource/AtchaColor/Colors.xcassets/Etc/kakao.colorset/Contents.json
  Atcha-iOS/DesignSource/AtchaColor/Colors.xcassets/Etc/kakaoLogo.colorset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/apple.imageset/Button Icon.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/apple.imageset/Button Icon@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/apple.imageset/Button Icon@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/apple.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/img_Step1.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/img_Step1@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step1.imageset/img_Step1@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/img_Step2.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/img_Step2@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step2.imageset/img_Step2@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/img_Step3.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/img_Step3@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/img_Step3.imageset/img_Step3@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/kakao.imageset/Button Icon.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/kakao.imageset/Button Icon@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/kakao.imageset/Button Icon@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Splash/kakao.imageset/Contents.json
  Atcha-iOS/Domain/Repository/LoginRepository.swift
  Atcha-iOS/Domain/UseCase/LoginUseCase.swift
  Atcha-iOS/Presentation/Login/LoginIntroCell.swift
  Atcha-iOS/Presentation/Login/LoginViewController.swift
  Atcha-iOS/Presentation/Login/LoginViewModel.swift
Labels: 🌐 Network, 👾 Feat

#32 [FEAT] Onboarding Flow 구현
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS.xcodeproj/xcuserdata/wodnd.xcuserdatad/xcschemes/xcschememanagement.plist
  Atcha-iOS/App/DIContainer/AppDIContainer.swift
  Atcha-iOS/App/DIContainer/CoordinatorFactory.swift
  Atcha-iOS/App/DIContainer/Onboarding/OnboardingDIContainer.swift
  Atcha-iOS/Data/Model/LoginDTO.swift
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/Data/Repository/OnboardingRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/OnboardingRepository.swift
  Atcha-iOS/Domain/UseCase/OnboardingUseCase.swift
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Onboarding/PushAlarm/PushAlarmViewModel.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewModel.swift
Labels: 👾 Feat

#40 [NETWORK] 장소 검색 API 연결
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Data/Model/OnboardingDTO.swift
  Atcha-iOS/Data/Repository/OnboardingRepositoryImpl.swift
  Atcha-iOS/Domain/Repository/OnboardingRepository.swift
  Atcha-iOS/Domain/UseCase/OnboardingUseCase.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewModel.swift
Labels: 🌐 Network

#41 [FEAT] 초반 Coordintaotr 및 Flow 개발
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/App/AppFlowCoordinator.swift
  Atcha-iOS/Data/Repository/UserRepositoryImpl.swift
  Atcha-iOS/Domain/Entity/User.swift
  Atcha-iOS/Domain/Entity/UserInfo.swift
  Atcha-iOS/Domain/Repository/UserRepository.swift
  Atcha-iOS/Domain/UseCase/FetchUserUseCase.swift
  Atcha-iOS/Presentation/Login/Coordinator/LoginCoordinator.swift
  Atcha-iOS/Presentation/Login/LoginViewModel.swift
  Atcha-iOS/Presentation/Splash/SplashViewController.swift
  Atcha-iOS/Presentation/Splash/SplashViewModel.swift
Labels: 🌐 Network, 👾 Feat

#45 [FEAT] FileStorage 개발 완료
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS/Core/Storages/FileStroage/FileStorable.swift
  Atcha-iOS/Core/Storages/FileStroage/FileStorage.swift
  Atcha-iOS/Core/Storages/FileStroage/FileStorageImpl.swift
Labels: 👾 Feat

#48 [FEAT] 마커 추가 및 실시간 좌표 불러오기
  .DS_Store
  Atcha-iOS.xcodeproj/project.pbxproj
  Atcha-iOS.xcodeproj/xcuserdata/wodnd.xcuserdatad/xcschemes/xcschememanagement.plist
  Atcha-iOS/Core/Util/LocationService.swift
  Atcha-iOS/Core/Util/UIImage+Ext.swift
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/current_location_mark.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/current_location_mark.imageset/Frame 1739333984.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/current_location_mark.imageset/Frame 1739333984@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/current_location_mark.imageset/Frame 1739333984@3x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/setting_location_mark.imageset/Contents.json
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/setting_location_mark.imageset/Frame 1739333984.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/setting_location_mark.imageset/Frame 1739333984@2x.png
  Atcha-iOS/DesignSource/AtchaImage/Icon.xcassets/Onboarding/setting_location_mark.imageset/Frame 1739333984@3x.png
  Atcha-iOS/Presentation/Onboarding/Coordinator/OnboardingCoordinator.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewController.swift
  Atcha-iOS/Presentation/Onboarding/HomeRegister/HomeRegisterViewModel.swift
  Atcha-iOS/Presentation/Onboarding/RegisterLocation/RegisterLocationViewController.swift
  Atcha-iOS/Presentation/Onboarding/RegisterLocation/RegisterLocationViewModel.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewController.swift
  Atcha-iOS/Presentation/Onboarding/SearchLocation/SearchLocationViewModel.swift
Labels: 👾 Feat
